"""MetadaSite Table

Revision ID: 286c34c5bc8d
Revises: 0df39ae9e394
Create Date: 2024-11-20 15:21:00.665793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286c34c5bc8d'
down_revision: Union[str, None] = '0df39ae9e394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('id_metadato', sa.Integer(), nullable=False),
    sa.Column('id_site', sa.Integer(), nullable=False),
    sa.Column('id_registro', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_metadato'], ['metadata.id'], ),
    sa.ForeignKeyConstraint(['id_site'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_site_id'), 'metadata_site', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_site_id'), table_name='metadata_site')
    op.drop_table('metadata_site')
    # ### end Alembic commands ###
