"""Added field named iterate to field_filter

Revision ID: 2fe63796d372
Revises: 
Create Date: 2024-10-14 23:29:32.616712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe63796d372'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_filters_filter_key', table_name='article_filters')
    op.drop_index('ix_article_filters_id', table_name='article_filters')
    op.drop_table('article_filters')
    op.drop_index('ix_facet_filters_filter_key', table_name='facet_filters')
    op.drop_index('ix_facet_filters_id', table_name='facet_filters')
    op.drop_table('facet_filters')
    op.drop_index('ix_user_auth_id', table_name='user_auth')
    op.drop_table('user_auth')
    op.drop_index('ix_field_filters_filter_key', table_name='field_filters')
    op.drop_index('ix_field_filters_id', table_name='field_filters')
    op.drop_table('field_filters')
    op.drop_index('ix_default_field_filters_id', table_name='default_field_filters')
    op.drop_table('default_field_filters')
    op.drop_index('ix_user_info_id', table_name='user_info')
    op.drop_table('user_info')
    op.drop_index('ix_default_article_filters_id', table_name='default_article_filters')
    op.drop_table('default_article_filters')
    op.drop_index('ix_default_facet_filters_id', table_name='default_facet_filters')
    op.drop_table('default_facet_filters')
    op.drop_index('ix_sites_id', table_name='sites')
    op.drop_index('ix_sites_name', table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('repository_url', sa.VARCHAR(), nullable=False),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.Column('fecha_modificacion', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sites_name', 'sites', ['name'], unique=False)
    op.create_index('ix_sites_id', 'sites', ['id'], unique=False)
    op.create_table('default_facet_filters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filter_key', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filter_key')
    )
    op.create_index('ix_default_facet_filters_id', 'default_facet_filters', ['id'], unique=False)
    op.create_table('default_article_filters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filter_key', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filter_key')
    )
    op.create_index('ix_default_article_filters_id', 'default_article_filters', ['id'], unique=False)
    op.create_table('user_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=False),
    sa.Column('apellido_paterno', sa.VARCHAR(), nullable=False),
    sa.Column('apellido_materno', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.Column('fecha_modificacion', sa.DATETIME(), nullable=True),
    sa.Column('user_auth_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_auth_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_user_info_id', 'user_info', ['id'], unique=False)
    op.create_table('default_field_filters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filter_key', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filter_key')
    )
    op.create_index('ix_default_field_filters_id', 'default_field_filters', ['id'], unique=False)
    op.create_table('field_filters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('site_id', sa.INTEGER(), nullable=True),
    sa.Column('filter_key', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.Column('fecha_modificacion', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_field_filters_id', 'field_filters', ['id'], unique=False)
    op.create_index('ix_field_filters_filter_key', 'field_filters', ['filter_key'], unique=False)
    op.create_table('user_auth',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_user_auth_id', 'user_auth', ['id'], unique=False)
    op.create_table('facet_filters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('site_id', sa.INTEGER(), nullable=True),
    sa.Column('filter_key', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.Column('fecha_modificacion', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facet_filters_id', 'facet_filters', ['id'], unique=False)
    op.create_index('ix_facet_filters_filter_key', 'facet_filters', ['filter_key'], unique=False)
    op.create_table('article_filters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('site_id', sa.INTEGER(), nullable=True),
    sa.Column('filter_key', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.Column('fecha_modificacion', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_filters_id', 'article_filters', ['id'], unique=False)
    op.create_index('ix_article_filters_filter_key', 'article_filters', ['filter_key'], unique=False)
    # ### end Alembic commands ###
