"""Create initial tables v4

Revision ID: 398c720e4ca8
Revises: 360497abebd9
Create Date: 2024-10-14 23:54:05.088450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398c720e4ca8'
down_revision: Union[str, None] = '360497abebd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_article_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filter_key')
    )
    op.create_index(op.f('ix_default_article_filters_id'), 'default_article_filters', ['id'], unique=False)
    op.create_table('default_facet_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filter_key')
    )
    op.create_index(op.f('ix_default_facet_filters_id'), 'default_facet_filters', ['id'], unique=False)
    op.create_table('default_field_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_key', sa.String(), nullable=False),
    sa.Column('iterable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filter_key')
    )
    op.create_index(op.f('ix_default_field_filters_id'), 'default_field_filters', ['id'], unique=False)
    op.create_table('user_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_auth_id'), 'user_auth', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('repository_url', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido_paterno', sa.String(), nullable=False),
    sa.Column('apellido_materno', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('user_auth_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_auth_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_info_id'), 'user_info', ['id'], unique=False)
    op.create_table('article_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('filter_key', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_filters_filter_key'), 'article_filters', ['filter_key'], unique=False)
    op.create_index(op.f('ix_article_filters_id'), 'article_filters', ['id'], unique=False)
    op.create_table('facet_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('filter_key', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facet_filters_filter_key'), 'facet_filters', ['filter_key'], unique=False)
    op.create_index(op.f('ix_facet_filters_id'), 'facet_filters', ['id'], unique=False)
    op.create_table('field_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('filter_key', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('iterable', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_filters_filter_key'), 'field_filters', ['filter_key'], unique=False)
    op.create_index(op.f('ix_field_filters_id'), 'field_filters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_filters_id'), table_name='field_filters')
    op.drop_index(op.f('ix_field_filters_filter_key'), table_name='field_filters')
    op.drop_table('field_filters')
    op.drop_index(op.f('ix_facet_filters_id'), table_name='facet_filters')
    op.drop_index(op.f('ix_facet_filters_filter_key'), table_name='facet_filters')
    op.drop_table('facet_filters')
    op.drop_index(op.f('ix_article_filters_id'), table_name='article_filters')
    op.drop_index(op.f('ix_article_filters_filter_key'), table_name='article_filters')
    op.drop_table('article_filters')
    op.drop_index(op.f('ix_user_info_id'), table_name='user_info')
    op.drop_table('user_info')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_user_auth_id'), table_name='user_auth')
    op.drop_table('user_auth')
    op.drop_index(op.f('ix_default_field_filters_id'), table_name='default_field_filters')
    op.drop_table('default_field_filters')
    op.drop_index(op.f('ix_default_facet_filters_id'), table_name='default_facet_filters')
    op.drop_table('default_facet_filters')
    op.drop_index(op.f('ix_default_article_filters_id'), table_name='default_article_filters')
    op.drop_table('default_article_filters')
    # ### end Alembic commands ###
