"""Add ietarable field to article_filter

Revision ID: 569dbd570a3e
Revises: 398c720e4ca8
Create Date: 2024-10-15 00:05:36.883113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569dbd570a3e'
down_revision: Union[str, None] = '398c720e4ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_filters', sa.Column('iterable', sa.Boolean(), nullable=True))
    op.add_column('default_article_filters', sa.Column('iterable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('default_article_filters', 'iterable')
    op.drop_column('article_filters', 'iterable')
    # ### end Alembic commands ###
