"""Add maps, default_map_filters, and map_filters tables

Revision ID: 971776e04f4e
Revises: 93804b030a28
Create Date: 2024-10-31 01:08:41.999398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971776e04f4e'
down_revision: Union[str, None] = '93804b030a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('collection', sa.String(), nullable=False, server_default='Cartíllas indígenas ILV'))
    op.create_index(op.f('ix_sites_collection'), 'sites', ['collection'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_collection'), table_name='sites')
    op.drop_column('sites', 'collection')
    # ### end Alembic commands ###
