"""Create initial tables v2

Revision ID: a53a21b4d353
Revises: 6fc0cf5e3b08
Create Date: 2024-10-14 23:43:05.303458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53a21b4d353'
down_revision: Union[str, None] = '6fc0cf5e3b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
