"""Add metadatos table

Revision ID: acf1a20bdf9c
Revises: b9a8d9a0e3af
Create Date: 2024-11-20 14:52:10.747780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf1a20bdf9c'
down_revision: Union[str, None] = 'b9a8d9a0e3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_map_filters_id'), 'map_filters', ['id'], unique=False)
    op.create_index(op.f('ix_maps_id'), 'maps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maps_id'), table_name='maps')
    op.drop_index(op.f('ix_map_filters_id'), table_name='map_filters')
    # ### end Alembic commands ###
